### ISSUE TITLE
Favorite button causes navigation on mobile

### ISSUE THREAD

**Issue by The-Noah** [bzlist/bzlist.net#3]
**Describe the bug**
If you favorite a server on mobile it causes navigation to the server details page. 

**To Reproduce**
1. Make sure the mobile layout is used (cards) 
2. Favorite any server on the homepage. 

**Expected behavior**
Favoriting a server on mobile shouldn't cause navigation, just like on desktop.

**Comment by royantar0311** [comment]
Hey! i fixed the issue and made a pull request, can you review it?

**Comment by The-Noah** [comment]
Thank you for fixing this!
