### ISSUE TITLE
Blank screen while hovering top server due to react error

### ISSUE THREAD

**Issue by bradwarwick** [bzlist/bzlist.net#5]
**Describe the bug**
On the home page while hovering mouse over the top server "Planet-M...com:4200" the page breaks with several console errors similar to the below (full log [here](https://github.com/bzlist/bzlist.net/files/6355598/bzlist.net-1619067540816.log)):
> Objects are not valid as a React child (found: object with keys {callsign, team, server, timestamp}). If you meant to render a collection of children, use an array instead.

**To Reproduce**
1. Go to home page
2. Hover top server

**Screenshots**
![image](https://user-images.githubusercontent.com/6638407/115657936-b4f9eb00-a32f-11eb-8767-9d51d5fc42ac.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89.0.4389.128

**Comment by The-Noah** [comment]
Thanks for the spot!

**Comment by The-Noah** [comment]
This should be fixed in d0f9aca7839c368c70811640cc25ff8f544ae94e.
