### ISSUE TITLE
Country flag images missing

### ISSUE THREAD

**Issue by bradwarwick** [bzlist/bzlist.net#6]
**Describe the bug**
Country flag images are currently missing as the third-party webserver is currently down. Perhaps they could be hosted locally?

**To Reproduce**
1. Go to home page

**Expected behavior**
Flags should always show

**Screenshots**
![image](https://user-images.githubusercontent.com/6638407/116382425-cea6a100-a80d-11eb-9cc7-03553ae2e4b4.png)
![image](https://user-images.githubusercontent.com/6638407/116382466-d8c89f80-a80d-11eb-974e-1f18d9dac617.png)

**Comment by The-Noah** [comment]
Thanks. I'll try to find some new ones, or probably make my own.

**Comment by The-Noah** [comment]
It seems the host was just temporairily down, as it's working again.

![image](https://user-images.githubusercontent.com/35819660/117374649-276fdc80-ae93-11eb-8e94-b98d9a2f8748.png)
